api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag)
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from re import L
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name="login"),
    path('logout/', views.LogoutUser.as_view(), name="logout"),
    path('register/', views.RegisterUser.as_view(), name="register"),
    path('', views.AllProfiles.as_view(), name="profiles"),
    path('profile/<str:pk>', views.UserProfile.as_view(), name="user-profile"),
    path('account/', login_required(views.UserAccount.as_view(),
         login_url='login'), name="account"),
    path('edit-account/', login_required(views.EditAccount.as_view(),
         login_url='login'), name='edit-account'),
    path('create-skill/', login_required(views.CreateSkill.as_view(),
         login_url='login'), name='create-skill'),
    path('update-skill/<str:pk>/', login_required(views.UpdateSkill.as_view(),
         login_url='login'), name='update-skill'),
    path('delete-skill/<str:pk>/', login_required(views.DeleteSkill.as_view(),
         login_url='login'), name='delete-skill'),
    path('inbox/', login_required(views.Inbox.as_view(),
         login_url='login'), name='inbox'),
    path('message/<str:pk>', login_required(views.ViewMessage.as_view(),
         login_url='login'), name='message'),
    path('create-message/<str:pk>/',
         views.CreateMessage.as_view(), name='create-message'),
]

projects/models.py
from email.policy import default
from enum import unique
from django.db import models
import uuid
from users.models import Profile

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()
        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together= [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
import uuid
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)


    class Meta:
        ordering = ['created']

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url

class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.subject)

    class Meta:
        ordering = ['is_read', '-created']
    

users/forms.py
from dataclasses import field
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = { 'first_name': 'Full Name' }


    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username',
                  'location', 'bio', 'short_intro', 'profile_image',
                  'social_github', 'social_linkedin', 'social_twitter',
                  'social_youtube', 'social_website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}

<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">{{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
              </li>
              {% endif %}

              {% if profile.social_twitter %}
              <li>
                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
              </li>
              {% endif %}

              {% if profile.social_linkedin %}
              <li>
                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
              </li>
              {% endif %}

              {% if profile.social_website %}
              <li>
                <a title="Personal Website" href="https://{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">

          {% for skill in skills %}

          <tr>
            <td class="settings__tableInfo">
              <h4>{{skill.name}}</h4>
              <p>{{skill.description}}</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>

          {% endfor %}

        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">

          {% for project in projects %}

          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id%}"><img src="{{ project.featured_image.url }}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id%}">{{project.title}}</a>
              <p>{{project.description|slice:"150"}}</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>

          {% endfor %}

        </table>
      </div>
    </div>
  </div>
</main>

  {% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}

  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">

        {% for message in messageRequest %}
        {% if message.is_read == False %}
          <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>

        {% endfor %}

      </ul>
    </div>
  </main>

{% endblock content %}

users/templates/users/login_register.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

{% if page == 'register' %}

<div class="auth">
    <div class="card">
        <div class="auth__header text-center">
        <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Register an Account</h3>
        <p>Create a new developer account</p>
        </div>
    
        <form action="{% url 'register' %}" method="POST" class="form auth__form">

        {% csrf_token %}

        {% for field in form %}

        <div class="form__field">
            <label for="formInput#text">{{field.label}}</label>
            {{field}}
            {% if field.help_text %}
                <small>{{field.help_text}}</small>
            {% endif%}

            {% for error in field.errors %}
                <p style="color: red;">{{error}}</p>
            {% endfor %}

        </div>

        {% endfor %}

        <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign Up" />
        </div>
        </form>
        <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login' %}">Log In</a>
        </div>
    </div>
</div>





{% else %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>

    <form action="" method="POST" class="form auth__form">
        {% csrf_token %}
      <!-- Input:Email -->
      <div class="form__field">
        <label for="formInput#text">Username: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="username"
          placeholder="Enter your username..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="Enter your password..."
        />
      </div>
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="{% url 'reset_password' %}">Forget Password?</a>
      </div>
    </form>
    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'register' %}">Sign Up</a>
    </div>
  </div>
</div>

{% endif %}

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}

  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          {% if message.sender %}
          <a href="{% url 'user-profile' message.sender.id %}" class="message__author">{{message.name}}</a>
          {% else %}
          <p class="message__author">{{message.name}}</p>
          {% endif %}
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>

  {% endblock content %}

users/templates/users/message_form.html
{% extends 'main.html' %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}

                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}
                </div>

                {% endif %}

                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profile_form.html
{% extends 'main.html' %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" action="{% url 'edit-account' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}

                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>

                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="{% url 'profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                  value="{{search_query}}" placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

        {% for profile in profiles %}

          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <gfd class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.imageURL }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                  </div>
                </gfd>
                <p class="dev__info">
                    {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                {% for skill in profile.skill_set.all|slice:"5" %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                {% endfor %}
                </div>
              </a>
            </div>
          </div>

        {% endfor %}

        </div>
      </div>
    </section>
    {% include 'pagination.html' with queryset=profiles custom_range=custom_range search_query=search_query %}
  </main>

{% endblock content %}

users/templates/users/skill_form.html
{% extends 'main.html' %}

{% block content %}

    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>
                <form class="form" method="POST">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    
                    {% for field in form %}

                    <div class="form__field">
                        <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                    </div>

                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>


{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.imageURL}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="https://{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}

              </ul>
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif%}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
            {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for topSkill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{topSkill.name}}</h4>
                <p class="devSkill__info">
                    {{topSkill.description}}
                </p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for otherSkill in otherSkills %}

                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{otherSkill.name}}</small>
                </span>

                {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in profile.project_set.all %}

              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id%}" class="project">
                    <img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' profile.id %}">{{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">

                        {% for tag in project.tags.all|slice:"5" %}

                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>

                        {% endfor %}

                      </div>
                    </div>
                  </a>
                </div>
              </div>

            {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}